language: python
python:
  - "2.7"
  - "3.3"
before_install:
  - sudo apt-get install liblapack-dev gfortran libblas-dev
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - pip install numpy
  - pip install scipy
  - pip install matplotlib
  - pip install Cython
  - python setup.py build_ext --inplace
script:
  - nosetests -s pymc/tests/
